# Configuration document of Golang CodeTeller

version = "0.1"

[language]
lang="Go"
version="1.10.3"
type="compiled" #The other type is interpriter

[keywords]
break = "break the execution"
default = "default case"     
func =   "function"  
interface = "interface type"   
select = "select statement"
case = "case when"        
defer = "defers"       
go = "go routine"
map = "map "            
struct ="struct type"
chan  = "channel "      
else = "if not the condition"
goto = "jumps to the label "
package =  "package named"    
switch = "switch condition"
const  =  "constant of "    
fallthrough = "fallthrough to"
if = "if the condition is "
range = "range  "       
type = " type of"
continue =  "continue upon"   
for = "for loop"
import =  "importing package "  
return ="returns "
var = "variable named  "

[operators]

[punctuations]

[literals]

[symbols]

[tokens]


[miscs]


